// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
}

declare module 'pg' {
  export class Pool {
    constructor(config: Record<string, unknown>);
    query<T = unknown>(queryText: string, params?: unknown[]): Promise<{ rows: T[] }>;
    end(): Promise<void>;
  }
}
