import { NextRequest, NextResponse } from 'next/server';

import {
  generateFollowUpEmail,
  buildFollowUpPlan,
  type LeadProfile,
  DEFAULT_LEAD,
} from '@/lib/agentic-engine';
import {
  fetchLeadDetail,
  recordInteraction,
  recordTask,
  type InteractionPhase,
} from '@/lib/db';

const toLeadProfile = (stored: {
  name: string;
  company: string;
  source: string;
  persona_tone: string;
  life_event: string;
  insurer: string;
  renewal_month: string;
  pain_point: string;
  preferred_channel: string;
}): LeadProfile => ({
  name: stored.name,
  company: stored.company,
  source: stored.source,
  personaTone: stored.persona_tone,
  lifeEvent: stored.life_event,
  insurer: stored.insurer,
  renewalMonth: stored.renewal_month,
  painPoint: stored.pain_point,
  preferredChannel:
    stored.preferred_channel === 'SMS' || stored.preferred_channel === 'Email'
      ? stored.preferred_channel
      : DEFAULT_LEAD.preferredChannel,
});

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as {
      leadId?: number;
      objection?: string;
      channel?: 'SMS' | 'Email' | 'Call' | 'Task';
      note?: string;
      dueAt?: string | null;
    } | null;

    if (!body?.leadId || !body.channel) {
      return NextResponse.json({ error: 'leadId and channel are required.' }, { status: 400 });
    }

    const detail = await fetchLeadDetail(body.leadId);
    if (!detail) {
      return NextResponse.json({ error: 'Lead not found.' }, { status: 404 });
    }

    const leadProfile = toLeadProfile(detail.lead);
    const objection = body.objection ?? leadProfile.painPoint;
    const email = await generateFollowUpEmail(leadProfile, objection);
    const plan = buildFollowUpPlan(leadProfile, objection);

    const phase: InteractionPhase = 'PHASE2';
    await recordInteraction({
      leadId: body.leadId,
      phase,
      channel: body.channel,
      summary: body.note ?? 'Follow-up action generated by Agentic Brain.',
      payload: { email, plan },
    });

    if (body.channel === 'Task') {
      await recordTask({
        leadId: body.leadId,
        phase,
        actionType: 'task',
        summary: body.note ?? 'Queue manual task from Agentic Brain.',
        dueAt: body.dueAt ?? null,
      });
    }

    return NextResponse.json({ email, plan });
  } catch (error) {
    console.error('Failed to record follow-up', error);
    return NextResponse.json({ error: 'Unable to store follow-up action.' }, { status: 500 });
  }
}
